cache:
  key: "$CI_COMMIT_REF_NAME-$CI_JOB_STAGE"
  paths:
    - .composer/

before_script:
  - apk add git --update

stages:
  - fluid
  
fluid:test:
  image: composer:1.6
  stage: fluid
  before_script:
    - export COMPOSER_CACHE_DIR=.composer
    - composer require typo3fluid/fluid-lint:dev-master
  script:
    - .Build/bin/fluidlint /Resources/Private/Templates/Default.html

