cache:
  key: "$CI_COMMIT_REF_NAME-$CI_JOB_STAGE"
  paths:
    - .composer/

before_script:
  - apk add git --update

stages:
  - test
  - lint

lint:typoscriptcgl:
    image: composer:1.6
    stage: lint
    before_script:
      - export COMPOSER_CACHE_DIR=.composer
      - composer require --dev helmich/typo3-typoscript-lint
    script:
      - .Build/bin/typoscript-lint -c tslint.yaml