cache:
  key: "$CI_COMMIT_REF_NAME-$CI_JOB_STAGE"
  paths:
    - .composer/

before_script:
  - apk add git --update

stages:
  - tslint

tslint:typoscriptcgl:
    image: composer:1.6
    stage: tslint
    script:
      - composer install --no-progress --no-ansi --no-interaction
      - .Build/bin/typoscript-lint -c tslint.yaml