<?php
/***************************************************************
 * Extension Manager/Repository config file for ext: "site_default"
 *
 * Auto generated by Extension Builder 2015-01-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Theme: Deafult Site',
	'description' => 'Purpose of the extension is to use as a default theme for the site, To manage backend/frontend layouts, templates, site global configuration, custom content elements and many more.',
	'category' => 'plugin',
	'author' => 'N/A',
	'author_email' => 'N/A',
	'author_company' => 'N/A',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.2.0',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'autoload' => array(
		'classmap' => array('Classes/')
	)
);
?>