# Load default processing options
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
editor:
  config:
   # contentsCss: "EXT:ns_basetheme/Resources/Public/css/RTE/bootstrap4-rte.min.css"
    stylesSet:
      - { name: "Lead", element: "p", attributes: {'class': 'lead'} }
    heading:
      options:
        - { model: 'paragraph', title: 'Paragraph' }
        - { model: 'heading1', view: 'h1', title: 'Heading 1' }
        - { model: 'heading2', view: 'h2', title: 'Heading 2' }
        - { model: 'heading3', view: 'h3', title: 'Heading 3' }
        - { model: 'heading4', view: 'h4', title: 'Heading 4' }
        - { model: 'heading5', view: 'h5', title: 'Heading 5' }
        - { model: 'heading6', view: 'h6', title: 'Heading 6' }
        - { model: 'formatted', view: 'pre', title: 'Pre-Formatted Text' }  
    toolbarGroups:
      - { name: clipboard, groups: [clipboard, undo] }
      - { name: editing, groups: [find, selection, spellchecker] }
      - { name: links }
      - { name: insert }
      - { name: tools }
      - { name: table }
      - { name: tabletools }
      - { name: document, groups: [ mode, document, doctools ] }
      - { name: others }
      - "/"
      - { name: basicstyles, groups: [ basicstyles, align, cleanup ] }
      - { name: paragraph, groups: [ list, indent, blocks, align, bidi ] }
      - { name: specialcharacters, groups: [ insertcharacters ] }
      - "/"
      - { name: styles }
    justifyClasses:
      - text-left
      - text-center
      - text-right
      - text-justify
    extraPlugins:
      - justify
      - font
      - find
      - bidi
      - selectall
      - autolink
    removePlugins:
      - null
    removeButtons:

# Allow s and u tag
processing:
  allowTags:
    - s
    - u

# Anchor class
classesAnchor:
  page:
    class: 'link-page'
    type: 'page'
  folder:
    class: 'link-folder'
    type: 'folder'
  file:
    class: 'link-file'
    type: 'file'
  external:
    class: 'link-external'
    type: 'url'
  mail:
    class: 'link-mail'
    type: 'mail'

# Custom class
buttons:
  link:
    properties:
      class:
        allowedClasses: 'link-arrow, link-page, link-folder, link-file, link-external, link-mail'
